### ISSUE TITLE
Images of Ryhiner collection: broken links

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#100]
The images of Ryhiner collection (Uni Bern - Zentralbibliothek) are still displayed in Detailansicht, while clicking the image or the "View this map" button shows an "image not available" page of the library. However, when searching directly in the library catalog, the images are still linked correctly to their records. This is a new bug, the function was OK probably until ca. mid-August. Test records:

http://search.kartenportal.ch/#id=044263570
http://aleph.unibas.ch/F/?local_base=DSV01&con_lng=GER&func=find-b&find_code=SYS&request=000976005

http://search.kartenportal.ch/#id=044451601
http://aleph.unibas.ch/F/?local_base=DSV01&con_lng=GER&func=find-b&find_code=SYS&request=001305141

**Comment by klokan** [comment]
This issue is combination of two problems:
1. Regression bug on #88. Work has started and we will fix the public web later today.
2. According your instruction from #30 we present the link from the first MARC field 856$u. For the record http://search.kartenportal.ch/#id=044263570 it has in SwissBib and in OAI right now a link: http://aleph.unibas.ch:80/F?func=service&doc_library=DSV01&local_base=DSV01&doc_number=000979399&line_number=0001&func_code=DB_RECORDS&service_type=MEDIA - which is not valid and must be fixed on the SwissBib side. This link is visible also at http://www.swissbib.ch/TouchPoint/perma.do?q=0%3D%22044263570%22+IN+%5B4%5D&v=nose&l=de

**Comment by zb-markus** [comment]
Well, my instructions of 10 May 2013 in #30 were on e-rara and e-manuscripta links. Unfortunately it seems that Swissbib handles Ryhiner links in another fashion than e-rara/e-manuscripta links. For Ryhiner the correct links are in the first 956$u. This is not exactly standard MARC usage that has links in 856$u. Please try to change from 856 to 956 for the Ryhiner images, but remain for e-rara and e-manuscripta on 856$u.

**Comment by klokan** [comment]
There are links in 856$u for Ryhiner which are now broken in SwissBib and must be fixed - this should be reported further to SwissBib people. If they already make changes - it would be great to put there links to the zoomable viewer instead - to be more unified with e-rara and e-manuscripta.

I am strongly against implementing rules for detecting the individual publishing systems and handling thumbnails and links for every single provider differently - why there would be the unified meta catalog otherwise?

We have now one rule/field for getting a thumbnail and one rule/field for getting a link - so the field inside of metadata for links and thumbnails is already unified on SwissBib side. Their rules for unification can be improved.
We have no metadata unification rules on our side and it is not systematic to introduce these during import from OAI-PMH.

P.S.
In future there should be also a unified thumbnail image service for all SwissBib records - with something like IIIF (http://www-sul.stanford.edu/iiif/image-api/) image server providing the thumbnails in a requested pixel size. We can implement such a service very efficiently with an open-source software developed for National Library of Austria for their Google Books project. But it goes beyond the scale of our existing contract.

**Comment by klokan** [comment]
Implementation issues on our side are now fixed and deployed in production.

SwissBib must fix the broken links for Ryhiner in 856$u and the Kartenportal search will get these via OAI-PMH the next day. If you click in SwissBib detail page on "URL: Vorschau zum Bild und Bestellfunktion" you will get the same broken link as on Kartenportal.

**Comment by zb-markus** [comment]
I have discussed this issue both with the Ryhiner collection manager and the map librarian liaison to Swissbib. The library is currently not able to guarantee stable links that will appear in a 856 field within Swissbib. On the other hand, it will take weeks or even months until Swissbib has time to work on maps matters.

Therefore I came to the conclusion that we omit Ryhiner images and links completely from our interface. In other words: Neither display thumbnail nor View this map button within Detailansicht of Ryhiner maps. Example: http://suche.kartenportal.ch/#id=044316038

**Comment by klokan** [comment]
Well - it seems the links runs again. I don't see a reason for removing these right now.

Kartenportal search on top of SwissBib database. All data from SwissBib appears in Kartenportal as well. It is very non-systematic to suddenly start to implement new rules for removing some of the content on our side.
Please think about it and comment on this subject.

**Comment by zb-markus** [comment]
We have several reasons to omit Ryhiner links:

(1) You strongly opposed to implement exceptions, especially links from 956 instead of 856. I fully agree.

(2) Currently, when one is clicking the View this map button, one is directed to a Copyright notice. If one clicks its OK button, one will be closed in because they deactivated the Back button of the browser. We do not like to support that behaviour, do we?

(3) If one has managed to actually see an image, it is disappointingly low-resolution. The real high-res images are for sale only. That is not what is expected by the user who already enjoyed the e-rara quality.

(4) With the links directly to the Bern library, we will sooner or later get problems again because they have the habit to change links without notice and without redirecting. Of course should new links appear in Swissbib and then in the Geosearch, but we have now seen that this is not a smooth procedure at all.

(5) As soon as the Ryhiner images are uploaded to e-rara, we will get a standard 856 link from Swissbib. At least during the upload procedure (that may take weeks or months depending on the library's workflow) we will either have (a) direct links to Ryhiner, (b) new links to e-rara, (c) or both of them. Therefore we need to deactivate the old direct links anyway in order to minimize confusion.

I am not talking about implementing a new rule but to omit an exception, i.e. to accept links within 856 fields only. Nothing else. It will reduce the complexity of the importing script or your code, too.

**Comment by klokan** [comment]
There is no exception to remove right now. In this moment we display only the links from 856$u and there are the same for Ryhiner, e-Rara and e-Manuscripta. See #30. 

If we should remove Ryhiner we have to implement a new exception instead. If we do that then there is not big difference whether we implement an exception for removing the record or for getting the link to zoomable viewer from one of the 956$u fields. It is hack in both cases.

So let me know whether: 
1) We keep the simple rule and links and thumbnails stay as they are (detais in #30).
2) We do implement an exception for Ryhiner and for
 2a) removing the record or
 2b) getting the zoomable URL

If 1) is your preference we can close the ticket.
If 2) is your preference please provide me with a proper a rule for how to detect a relevant record on which the rule apply and for 2b) also how to systematically recognise which of 956$u records is the right one.

P.S.
Greetings from Bernhard Jenny from ICC2013.

**Comment by zb-markus** [comment]
I see that we have to independent problems, and I apologize for having mixed these above. 

The first one, the broken links, are OK again after all worked well already in July. I do now know that the problem was a temporary one in mid-August. And it was neither caused by Geosearch, nor by Swissbib. It was the Bern library that reorganized its website and therefore temporarily caused broken links. I will have a word with them.

The second problem came into this discussion because I mentioned in my comment of 21 August that the correct Ryhiner links are in 956 fields. When writing this I had the Lastenheft in mind that says (F.20) that only high-res images should be linked, while low-res ADAM images should be ignored. This would in fact call for a hack in order to link to high-res Ryhiner images. On the other hand, we try to push the Bern library towards e-rara. Once they upload the high-res images to e-rara, they will become available to Swissbib and Geosearch through the standard 856 field. There is no guarantee that they will change their presentation mode of Ryhiner images in near future, though. In the meanwhile we accept to show and link low-res Ryhiner images. We therefore agree to keep the simple rule and therefore links and thumbnails stay as they are.

One small change needs to be introduced anyway: When clicking the View this map button, a new browser window should open that will display the content of e-rara, e-manuscripta and Ryhiner. When done, you can close the ticket. Thank you - and best wishes for your holidays.

**Comment by zb-markus** [comment]
A new problem was detected today: All images except of the Ryhiner images have gone, i.e. e-rara and e-manuscripta images are no longer shown. Please come back to the situation we had until 31 August. See 
http://search.kartenportal.ch/#id=045311757
http://search.kartenportal.ch/#id=131358952

**Comment by klokan** [comment]
#119 "View this map" opens a new window
#120 Thumbnails for e-rara and e-manuscripta missing

Please open for new requests and new problems new tickets.

I am closing this ticket - the broken links to Ryhiner were discussed and are solved now.
