### ISSUE TITLE
Link from Kartensuche library name to Sammlungen

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#102]
J suddenly noticed that we didn't implement the link from the Kartensuche libraries to the Sammlungsverzeichns (a requirement that we stipulated.):

![info](https://f.cloud.github.com/assets/4223790/1007197/6ec62e24-0b01-11e3-9a8b-d5ced76b9a1c.jpg)

**Comment by klokan** [comment]
According to the original mockup made by the designer this should look similar to:

![detail-popup](https://f.cloud.github.com/assets/59284/1020744/cb478830-0cc0-11e3-9752-de28b85bff93.jpg)

We should round the link buttons (5px) but keep only the existing short captions used by now.
Instead of the address we will display blue underlined textual link with "Library details" going to "http://www.kartenportal.ch/library/E01/" where E01 is the SwissBib identifier.

**Comment by klokan** [comment]
Done.
