### ISSUE TITLE
Administration: libraries interface

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#113]
Please leave out the marked features (allready specified in previous tickets, some features must be new):

![interface_libraries](https://f.cloud.github.com/assets/4223790/1067954/125dc042-13e0-11e3-88e2-f041a3b23439.jpg)

Please translate all texts and titles.

**Comment by JackuB** [comment]
Libraries now don't have ability to upload files (so that button for file upload is hidden)
Admin UI settings from user "testlib" are now copied to all users
Strings from library interface (add new posts etc.) are now added to .po/.mo files as they are now translatable and in same textdomain as rest of theme.
