### ISSUE TITLE
Links from Kartensuche to library detail pages

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#115]
Link 'library details' can only be displayed if library is included in the libraries directory:

![link](https://f.cloud.github.com/assets/4223790/1071855/5becce92-1480-11e3-8887-0c5f57eeb606.jpg)

**Comment by klokan** [comment]
This is going to be fixed once we move the website to www.kartenportal.ch - because we can't implement it immediately due to password protection and not final domain.

We will display the postal address always and the link to Library details only if it has the SwissBib identifier as identifier on Kartenportal.

**Comment by klokan** [comment]
The swissbib.js contains a true/false value for each library as the last attribute in the list -  telling whether to display the link or not.

**Comment by petrsloup** [comment]
New element will be appended to each entry in swissbib.js. 0 meaning "don't display", 1 meaning "display the link".

**Comment by keosak** [comment]
All right, the new field is present at http://search.kartenportal.ch/swissbib.js as the last item in each sublist. For the time being it is generated from a static HTML file that I have downloaded. We will switch to regular updates when the Kartenportal site goes live.

**Comment by klokan** [comment]
Done and deployed. The need to automate is marked in post-launch ticket.
