### ISSUE TITLE
Languages after searching the site or choosing a term from tags

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#155]
When J search the site and come to the result page it is not possible to change the language. The other languages buttons are linked to the home page in this case.

**Comment by JackuB** [comment]
There are technical difficulties when you'd want to change lang when searching... We are using similar url matching/redirecting on user profiles and it works there, because we know the structure of library name (single string), but search results is whole another story as search string could be anything.

I really don't see user case for switching languages when searching. Enter site (remember that search results are not visible for search engines, so user can't find them directly) -> search for something -> and then switch language to your native.

If it's ok, I'd like to skip this feature as it could create more problems then it would solve.

**Comment by JackuB** [comment]
Thing with tags is, they can't be lang switching, as each tag exists separated in each language (so we can have tag cloud for each lang). You can see it here: http://kartenportal.klokantech.com/wp-admin/edit-tags.php?taxonomy=post_tag&lang=de&post_type=announcement

![image](https://f.cloud.github.com/assets/1788727/1203259/28272e68-2551-11e3-979e-804e26801b04.png)

Every language have its own tags and own tag cloud and there is no connection for them. If we'd like to have connected (translated) tags it would really 1) make working with tags much harder, as someone would have to manage translations of newly created tags and/or manually (and it's not that easy) link them with other tags from other languages 2) tag cloud might get messy, as it would weight importance of tag to translation of tags to other languages and I'm not sure how it would behave if tag wouldn't be translated.

**Comment by ethbib-susanne** [comment]
It is o.k. if there is a tag cloud in every language. If articles are not translated, tags won't be neither. Just leave it the way it is.

You are right, that there is no reason to change language when searching. Skip the feature.

**Comment by ethbib-susanne** [comment]
Maybe we will have to come back to this in the future. It is not nice if somebody is directed to the starting page if he just wants to change the language. Did J understand properly that it is complicated to solve this problem?
