### ISSUE TITLE
Fields 1st and 2nd Column Map Collections directory

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#19]
There are some changes/corrections concerning descriptions, number and alignement of fields:

1st COLUMN

![verz1](https://f.cloud.github.com/assets/4223790/420596/7b964dfe-acf2-11e2-9503-f80a1f1f6884.jpg)
2nd COLUMN
![verz2](https://f.cloud.github.com/assets/4223790/420598/9b7f6948-acf2-11e2-97b5-02483f703d6b.jpg)

In order to give instructions concerning syntax of texts and values to the map libraries  there should be an example at the end of each field. How will we solve the problem of multilingualism?

**Comment by klokan** [comment]
Please provide these as text for copy&paste, otherwise we have to retype the fields from your images and it introduces new errors.

We need also the English version - and in English should be probably also columns in the Excel sheet with all the data for all libraries you want to display.

Translation of the values could be possibly passed trough the GetText, but we need to investigate this further after we have the data in native language imported in the system.

In my notes I have that the opening times are not going to be displayed, because they are changing too much. It has changed?

We need from you the complete database, discussed #13

Thanks.

**Comment by klokan** [comment]
The texts and columns from Susanne are in our intranet: https://docs.google.com/a/klokantech.com/spreadsheet/ccc?key=0AgUe1kqIRJWSdHhJa3RIazFWNWt6a28xa2JOanE3YVE&usp=sharing

**Comment by klokan** [comment]
Formatting of the text should be applied in #2. Closing.
