### ISSUE TITLE
CMS Updating problem URGENT

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#196]
J updated the 'Anleitung für Kartensammlungen' Seite in French and Italien and lost all texts including the German version that J didn't update. What is the problem. Can you restore the texts in German, French and Italian? 

J haven't seen the following feature before. Maybe this is the reason for the problems:

![problem](https://f.cloud.github.com/assets/4223790/1557018/3c1b927a-4ef9-11e3-97a7-f35d1a3b5780.JPG)

**Comment by klokan** [comment]
I restored the original german version from the backup and configured all the pages so you can work on translations directly.

The text were overwritten by your edits, because the page was set in a mode where one language is available to all translations so you was always overwriting.

See:
http://www.kartenportal.ch/anleitung/
http://www.kartenportal.ch/en/instructions/
http://www.kartenportal.ch/fr/instructions/
http://www.kartenportal.ch/it/anleitung/

The french stub of the translation is copied in the front of the article and followed by German original with pictures, so you can merge these easily.

**Comment by klokan** [comment]
The issue reproduced. It happens with non-admin users. We are working a a fix.

**Comment by ethbib-susanne** [comment]
For the 'e01' user J don't need rights to act as a admin. 'e01' is a common map library user.

Please take note that at the moment as 'kartenportal' admin J don't have rights to access the interface for translations (localization). J get an error message. Please check and give all necessary rights to the 'kartenportal' user.

**Comment by JackuB** [comment]
I have identified issue and changed behavior of language switching (which was root cause here). Please test and let me know if you encounter any other issue (writing/editing posts should be without problem now)
