### ISSUE TITLE
Interface for map series: improvements

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#208]
Mockups for improved user interface for map series:

![kartenportal-webdesign-sheets-show 1](https://f.cloud.github.com/assets/59284/1725210/b1618044-627c-11e3-8ab2-ee8c7180c613.jpg)

![kartenportal-webdesign-sheets-hide](https://f.cloud.github.com/assets/59284/1725212/b654f45a-627c-11e3-8e05-3aa42809e355.jpg)

We have prepared a new symbol for the tool integrating the map series into interface.

Suggested improvements:
- Blue control for map series always on the same place in the detail window
- Symbol used in the dialog window
- Redesigned hover box on top of the map for sheets under the mouse
- Link back to "Available maps >"
- (optional) number of sheets in the series (implementation requires server changes)
- (optional) hover interaction can highlight actual sheet (implementation requires server changes)

**Comment by ethbib-susanne** [comment]
- Blue control for map series always on the same place in the detail window >> YES
  - Symbol used in the dialog window  >> YES, TEXT AND SYMBOL ARE PERFECT
  -  Redesigned hover box on top of the map for sheets under the mouse >> LOOKS VERY NICE.
  -  Link back to "Available maps >" >> THIS J DON'T UNDERSTAND
  -  (optional) number of sheets in the series (implementation requires server changes) >> NO. NICE BUT FOR THE ACTUAL USE NOT NECESSARY.
  -  (optional) hover interaction can highlight actual sheet (implementation requires server changes) >> WOULD BE MORE USER FRIENDLY - DOES NOT HAVE HIGHEST PRIORITY. IF THERE IS TIME LEFT YES.

MAYBE WOULD BE GOOD FOR USER INTERACTION, IF THERE WAS IN ADDITION A 
![kreuz](https://f.cloud.github.com/assets/4223790/1735967/a01f6e90-635d-11e3-8cde-c40fb8a4dd78.JPG)
ON THE RIGHT SIDE ABOVE THE MAP WINDOW IN ORDER TO LEAVE THE SPECIAL MODE.

**Comment by klokan** [comment]
@ethbib-susanne Thanks for the feedback - we are implementing it now.

**Comment by klokan** [comment]
Done and deployed.
