### ISSUE TITLE
Map series variable spelling

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#212]
Here is the list of map series sorted by number of sheets:

http://api.kartenportal.ch/series-count.txt

and alphabetically:

http://api.kartenportal.ch/series-alpha.txt

There are issues in metadata which should be fixed manually probably. Some of records may belong together but they do not because of spelling of the name of the series:

650 Jahre Stadt Oldenburg 1:25 000|2
650 Jahre Stadt Oldenburg, 1:25 000|1
Africa 1:2 000 000|73
Africa 1:2,000,000|1
Afrique 1:500 000|7
Afrique 1:500,000|3
Agfa Tourenkarte|3
Agfa-Tourenkarte|1
Aktuelle JRO/Seydlitz Landkarte|9
Aktuelle JRO/Seydlitz-Landkarte|10
Australia 1:250 000 geological series|2
Australia 1:250'000 geological series|9
Geological map of New Zealand 1:50 000|14
Geological map of New Zealand 1:50000|11
Geological survey of Nigeria 1:250 000|32
Geological survey of Nigeria 1:250000|16
etc.

@eth-susanne Can you please comment on this? Solution may be also 490$w mentioned in #210

**Comment by zb-markus** [comment]
According to the cataloguing rules, the series name has to be entered in 490 $a in the form it is shown on the map. For the Swiss national map series, 490 $a may therefore read either Landeskarte der Schweiz 1:25 000, Carte nationale de la Suisse 1:25 000 or Carta nazionale della Svizzera 1:25 000. These variants are correct and could only matched together via 490 $w. 

However, this is quite an exception. The examples cited above by Klokan show typographical variants that need to be corrected in the library catalogues. Allmost all existing map series are in one language only, and have therefore no reasonable variants within 490 $a. 

From my point of view this ticket can be closed until a real problem is found where series do not match due to correct variants within 490 $a. I think we can accept for the moment that the Swiss national series do not perfectly match now (actually they do because some libraries have not catalogued according to the rules ...).

**Comment by klokan** [comment]
Thank you Markus for the comments.

I am aware that the metadata must contain exactly what is written on the physical map. Still, there is possible inconsistency in spelling on series names in cases such as:

"Geological map of New Zealand 1:50 000" with 14 sheets
"Geological map of New Zealand 1:50000" with 11 sheets
or
"Geological survey of Nigeria 1:250 000" with 32 sheets
"Geological survey of Nigeria 1:250000" with 16 sheets
or even
"Australia 1:250 000 geological series" with 2 sheets
"Australia 1:250'000 geological series" with 9 sheets
and many others - where these may belong together in fact.

A single map index with joined sheets will be shown instead of two different indexes in case such two series names are unified.

We have provided the generated list of all series available via Kartenportal - with names and number of sheets - for possible review by librarians. The links to these lists are above.

There are also some strange series name - probably a mistake when sheet number was written into the MARC field for series name - see the top of the list sorted by alphabetical order.

If these or similar changes happen in future we may need to manually reset a cache of the map series tiles - so the updates are visible on the website and in the map index overlay. The cache is set in this way for the performance reasons.

Field 490$w is not processed and used at this point - discussed in #210.

Closing this ticket according the suggestion.
