### ISSUE TITLE
Map series icon + look & feel changes

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#221]
Look&feel adjustments and series icon visibility changes are requested under this ticket.

**Comment by ethbib-susanne** [comment]
Markus made a very nice suggestion for issue #217 and #221. The concrete works are:
1. Adapt the displayed representation of metadata according to the mock-up.
2. Position the 
   ![icon1](https://f.cloud.github.com/assets/4223790/2009746/71c80c3a-8763-11e3-96d2-21fed6145712.jpeg) open map index icon according to the mock-up. Click on the icon as well as click on the link connected to the series name in the metadata opens the series mode.
3. Add the close map index icon in the series mode according to the mock-up.
4. Remove the 
   ![icon2](https://f.cloud.github.com/assets/4223790/2009760/b2a7edb0-8763-11e3-8e12-29208b5dfe68.jpeg) icon in the series mode.
5. Highlight the sheet that is run over by the mouse. (Priority 2: If J remember correctly - this issue includes work on server side of the application)
6. Map series info box: [text Markus] - discussed in a separate ticket #230

Mock-ups:
![vorschlag detailansicht](https://f.cloud.github.com/assets/4223790/2009652/0b0bdd60-8762-11e3-9db6-54a1fca460df.jpg)

![vorschlag kartenmodus](https://f.cloud.github.com/assets/4223790/2009653/0b287b0a-8762-11e3-8e3d-c975509d1a8e.jpg)

Petr, please give feedback. How many hours is your estimate for this works.

**Comment by klokan** [comment]
The request to change the look&feel according the mockup is 1-3 hours to implement, test and deploy.
True tracked time is going to be invoiced and time sheets provided.

Be aware, that the vertical position of the blue "series" icon is going to be variable and "jump" up and down, if you scroll over more items with series information in the normal results view. In this moment it has been on a fixed position. Otherwise I like the new mockup very much.

Questions:
- Q1: In the second mockup you kept the gray "X" but in the point 4 you ask for removal. Shall it stay there or be removed?
- Q2: I expect to keep titles for "Editions" and "Series" as they are. Or do you need change and new translations in more languages?
- Q3: Point 5 is approx. 8-12 hours of work. I think this will improve the user interaction significantly. We must reindex the whole database, make changes in the client-server protocol and changes in the JavaScript user interface, testing and new deployment.

**Comment by ethbib-susanne** [comment]
Q1: The gray "X" should be removed. It is replaced by the new 'hide' Icon

Q2: 
DE: Andere Auflagen, EN: Other editions, FR: Autres éditions, IT: Altri edizioni

DE: Reihe, EN: Series, FR: Série, IT: Serie
Translations via translation tool same as other terms.

Please go ahead and go to a maximum of 12 hours for all described improvements. Point 5 has Priority 2. Please decide at the start of implementatin of point 5 if you can do it or not within the time frame.

Afterward please send the final invoice. Can you estimate when you have finished this work?

**Comment by klokan** [comment]
Thanks for the answers.

We schedule the work now and I expect to finalise the whole contract by mid-february.

(the discussion related to the info window (Q6) is moved to #230. It is unrelated to "series icon" which is the title of this ticket)

**Comment by ethbib-susanne** [comment]
Please finalize the works and send the final invoice. Thank you.

**Comment by klokan** [comment]
The latest version is online. Please verify.

**Comment by ethbib-susanne** [comment]
Very nice! Very user friendly!
Final feedback tomorrow when Markus also verified it.

**Comment by zb-markus** [comment]
Looks nice indeed. 

Regarding the functionality there is still a bug (atl least in IE8 and IE9): When one has found a record, and opens the map series mode, then one is sometimes unable to highlight or select adjacent sheets with mouse-over or even with click. Example: ONC sheet C-4 (http://klokan.github.io/maprank-client/index.de.html#series&id=195707680). I could select adjacent sheets B-1, 1-2, C-2, C-3, but I was unable to select sheets D-3, D-4, D-5 by mouse-over or simple click, although double-click always worked. It seems that this bug appears by random. For instance when one searches for another series, everything may be OK there, and when one returns to the previous series the selectable and non-selectable sheets show a different pattern.

**Comment by ethbib-susanne** [comment]
The bug can be reproduced in Firefox 26.0

**Comment by klokan** [comment]
This is irrelevant to "Map series icon". A new issue #239 opened.
