### ISSUE TITLE
Layout services webpage

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#24]
I am sorry but the new layout on the services wegbpage with thumbnail navigation is in my view clearly overloaded. We should after all use a bread crumb trail for navigation on this page.

Another thing is the 'worth knowing about maps' webpage. The thumbnail navigation might be nice on that page. There should be a bit more space between main picture/text and thumbnails.

**Comment by klokan** [comment]
Susanne, this form of navigation has been agreed on our last meeting and mocked up by designer on #10. Now we have implemented it in HTML, and you are requesting a change after all of this is done. We are loosing time and wasting effort.

Please make your definitive and final decision and write it here. We will then do what you order.

My notes from the last meeting regarding navigation in Services:
- If we use bread crumb trail the only navigation is going to provide only link to the parent page - which is already available via the menu Services anyway. It makes no sense in my opinion.
- We were discussing as an alternative the Next and Previous links, possibly with thumbnails, but we agreed on thumbnails under the main image, because you can jump to the service you want to see directly.

**Comment by ethbib-susanne** [comment]
Your are right and J still like the concept for the ‘Wissenswertes über Karten’ webpages. The concept for this page was defined accordingly from the beginning.

For the services webpage J always required a bread crumb trail. In the last meeting you persuaded me to make an attempt with the thumbnail concept (J envisioned that the thumbnail would be smaller ). Now J don’t like it at all and you will agree that the layout is much too crowded. We can’t leave it this way.

**Comment by klokan** [comment]
There is one more suggestions for the layout change from the designer:

![kartenportal-webdesign-services](https://f.cloud.github.com/assets/59284/708115/372d42f6-de3b-11e2-9aa3-64b85befc821.jpg)

Either we stay with the original or use this new one. Decision by @ethbib-susanne is required.

**Comment by ethbib-susanne** [comment]
New layout for services page confirmed. Thank you for the new suggestion that J like.

**Comment by klokan** [comment]
TODO:
- Remove the two existing implemented layouts (one http://kartenportal.klokantech.com/articles/, http://kartenportal.klokantech.com/blog/ausstellungen-und-fuhrungen-besuchen/) and replace it with a single layout. This layout is exactly the same as for map gallery.
- The /services/ and Services should be used everywhere - replace the URL and titles, as well as the menu in the administration section. In german it is "Angebote".
