### ISSUE TITLE
Back links to ZB catalog incorrect

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#246]
Some back links are missing. For example, record http://klokan.github.io/maprank-client/index.de.html#id=298417499 has back links to ETH and others, while the back link to Zentralbibliothek Zürich is missing. However, the same record in Swissbib https://www.swissbib.ch/Record/298417499 has working links also to Zentralbibliothek Zürich.

Other examples:
http://klokan.github.io/maprank-client/index.de.html#id=289098548
https://www.swissbib.ch/Record/289098548

http://klokan.github.io/maprank-client/index.de.html#id=168892812
https://www.swissbib.ch/Record/168892812

**Comment by klokan** [comment]
I expect you mean a missing links between Kartenportal.CH website and geosearch, so to http://www.kartenportal.ch/library/Z04/

The new SwissBib reports that all the "Zentralbibliothek Zürich" library holding of map records are now "Z01" not "Z04" as before. Is this correct and expected from SwissBib?

If it is correct and we should just fix the links we must manually change the identifiers of the libraries on the Kartenportal.CH website (http://www.kartenportal.ch/kartensammlungen/) and the related identifiers. This means instead of http://www.kartenportal.ch/library/Z04/ we will need http://www.kartenportal.ch/library/Z01/.

Reported changes in the library identifiers so far:

| New ID | Old ID | Note |
| --- | --- | --- |
| Z01 | Z04 | Zentralbibliothek #247 |
| AX040 | AX40 | Swisstopo  #247 |
| NB001 | 10000 | National Library #247 |

**Comment by zb-markus** [comment]
I mean the back links from the Detailansicht to the individual catalogs (the red buttons). For example, the Detailansicht of record http://klokan.github.io/maprank-client/index.de.html#id=289098548 shows 5 red buttons for 5 different libraries: ZB Zürich, ETH, etc. Clicking the button for Zentralbibliothek Zürich shows NEBIS without call mark, while cklicking the button for ETH shows NEBIS with call mark. The same record in Swissbib https://www.swissbib.ch/Record/289098548 shows correct call marks for all libraries.

The Swissbib MARC view shows that the identifier for the Zentralbibliothek Zürich is indeed set to Z01 (while internally in NEBIS it is still Z04). This is not expected, but Swissbib may have reasons to change some ientifiers for their purposes. We have to deal with what Swissbib provides us. Therefore it could work if you simply change all Z04 into Z01, and similarly for Swisstopo and the National Library. That would solve #247 as well.

**Comment by klokan** [comment]
This has been fixed during the switch of the servers and it runs now.

Still - from the SwissBib we are getting a wrong URL template.

This has been now communicated further to Gunter.

Please verify, in case there are issues we can reopen this ticket.

**Comment by zb-markus** [comment]
Tested (for ZB Zürich, Swisstopo, National Library) and accepted.

**Comment by klokan** [comment]
Comments from Tobias:

> In swissbib we built a backlink-mechanism that uses 949 $b for the backlink and 949$F for display.  This gives us the opportunity to bundle all the different codes (949$b) used for one library in one code (949$F) that we use for display, favorites and filtering. This is combined code is also put in our librarynames-file whereas the other is taken for the communication with the library system. This means that you have to fill «&sub_library=» with «949$b» and use «949$F» for the display of the name.
> It is not a very frequent case (roughly 30 out of 900 libraries)

**Comment by klokan** [comment]
Decission: for now we keep only exception for the Z01 / Z04. This ticket is closed now.

A complete proper implementation having the link library identifier different from the filter/display library identifier would require new changes in the way Kartenportal handles identifiers. This is a possible new request introduced by the new SwissBib just now.

If this is required to run properly or new related linking issues are reported, we should open a new ticket specific to this problem and schedule the development (@zb-markus)
