### ISSUE TITLE
K.1.5 - Map series: deleted records shown - OAI sync

### ISSUE THREAD

**Issue by hynekpridal** [klokantech/kartenportal-tickets#278]
Deleted records in Swissbib should not be visible in the map series overview.

Example:
Carte de l'Afrique de l'ouest au. 1: 200 000 Bl R 11 [1954] 
was in NEBIS and Swissbib deleted in the past, but it is still visible in Kartenportal:

http://suche.kartenportal.ch/#series&id=18489624X 
http://suche.kartenportal.ch/#id=183362888

deleted record (1954):
![deleted](https://cloud.githubusercontent.com/assets/8998570/4494260/147cb336-4a50-11e4-8dd9-2a28100191b7.png)

correct record (1964). The deleted record (1954) CANNOT be shown anymore
![correct](https://cloud.githubusercontent.com/assets/8998570/4494282/38b673e0-4a50-11e4-8cfb-e5da97fcb48a.png)

**Comment by keosak** [comment]
In response to the `Identify` OAI-PMH verb, the Swissbib server responds with `deletedRecord = transient`. This was not the case with the old server. According to the protocol specification:

> `transient` - the repository does not guarantee that a list of deletions is maintained persistently or consistently. A repository that indicates this level of support _may_ reveal a deleted status for records.

Source: http://www.openarchives.org/OAI/openarchivesprotocol.html#DeletedRecords

The server doesn't support incremental harvesting with respect to deleted records, hence it doesn't work properly.

I will experiment with shorter harvest intervals. However, Swissbib should either set up a server with persistent record deletion support, or at least provide us with the correct interval for reliable harvesting. Otherwise we have to fall back to downloading the whole dataset for every update. This is prohibitively expensive to do frequently and would have to be done only occasionaly. Hybrid strategy is possible as well, where we do a full harvest once a week and incremental harvests every day.

**Comment by klokan** [comment]
Let's go for the hybrid strategy now. Once a week a full harvest, every day incremental @keosak.
That's all what we can do to improve reliability of the Kartenportal sync with the existing SwissBib server.

We need from SwissBib information about their preferred proper solution - if it is possible to provide a correct information about deleted records via OAI-PMH incremental harvesting, as it was available on the original server.

**Comment by keosak** [comment]
Pending information from Swissbib, we have adopted the following procedure. Every Sunday we do a full harvest. Every other day we do an incremental harvest on top of the data from previous day.

**Comment by ghost** [comment]
FROM:zb
Will both the full and the incremental harvesting run automatically? 

Do we have extra costs because of the hybrid harvesting strategy?

**Comment by ghost** [comment]
The harvesting is automated.
There are no extra costs.

**Comment by ghost** [comment]
FROM:zb
In Detailansicht of record http://suche.kartenportal.ch/#id=258660600 the following earlier editions are listed: 
... 2001 1995 1995 1990 ... 

When one clicks on either of the year 1995, both change its colour to black indicating that there is actually only one record for the 1995 edition (http://suche.kartenportal.ch/#id=258660643) that nevertheless shows up twice. Please investigate whether this is a leftover.

See e-mail with attached image.

This phenomenon is reproducable for other records, compare for example the Detailansicht for record  http://suche.kartenportal.ch/#id=265486092.

**Comment by hynekpridal** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/8998570/4739370/2a47942e-5a04-11e4-9d70-7c28928aff10.png)

**Comment by ghost** [comment]
FROM:zb
I just noted that in the cases shown above (i.e. when records show up twice) there are 2 MARC 034 fields within the same record. This is a Swissbib problem and it has nothing to do with the present issue here. Please close issue.

Tested and accepted.
