### ISSUE TITLE
A.1.4 start page, showing event dates

### ISSUE THREAD

**Issue by ghost** [klokantech/kartenportal-tickets#290]
FROM:zb
When an event appears on the start page, the date immediately below the event title should be the date of the event, not the date when the event was blogged.

Example: the current event in the left column (Kolloquium zu historischen Orthophotos) was written on 31 March. That date should be hidden. Instead, the date when the event will take place should be shown, that is 17 April.

**Comment by ghost** [comment]
FROM:zb
Why is the label of this issue @eth by the way?

**Comment by klokan** [comment]
We will display the date of the event - but order of the news mixed with the events must be according their publishing date (only the latest one will appear).
This may case confusion to the users as the order makes not much sense once we display the date of the event only - and this is the primary reason why there were two distinct lists originally.

Let's display the event date - if this is ordered.

@eth is set in the clientportal because general support tickets for Kartenportal project should be submitted by email to both zb and eth and both should be able to comment and see these...

**Comment by ghost** [comment]
FROM:zb
We need the event date displayed. Perhaps with the new CMS it becomes possible to (a) order the events according to event date, and (b) to display both event and publication dates, for example:

Event XY
14 April 2015 - 15 April 2015
text text and text text and text text etc
published: 31 March 2015

@eth is OK of course. I was confused because @eth was the only label and @zb was missing ... No action needed, though.

**Comment by eth-zz** [comment]
Please stop including/tagging username @eth I have nothing to do with this project.

**Comment by daliborjanak** [comment]
Implemented. If post is event that is displayed event date. Unless the publication date is displayed. Please verify

**Comment by ghost** [comment]
FROM:zb
Tested. The display of dates (event dates, publication dates) needs to be reviewed again under the new CMS. 

Please close.
