### ISSUE TITLE
A.1.2 Menu font size

### ISSUE THREAD

**Issue by ghost** [klokantech/kartenportal-tickets#295]
FROM:zb
The top menu bar font size has been reduced due to the additional menu item. That is an acceptable solution. However, we think that the font size is now rather small. However, there is still room to both left and right of the menus. Try top menu bar font size a little larger, perhaps plus 1 pt.

**Comment by klokan** [comment]
The problem is the length of the new menu. With one size bigger font the layout already breaks:
![screen shot 2015-04-08 at 10 29 19](https://cloud.githubusercontent.com/assets/59284/7041530/50074970-ddda-11e4-86c0-a141f0fb231e.png)

Nice menus has short single word titles. Long two words titles are against usability and makes the website harder to read and ugly, and are enforcing smaller fonts.

I believe the "Learn" (suggested in the Quote document) would make equally good top menu for the presented content - and it is easily translatable - unlike  "Wissenswertes", with long unnatural translations such as "Informazioni interessanti" and "Ce qu'il faut savoir".

Please comment - as there is no action to do on this ticket right now.

**Comment by ghost** [comment]
FROM:zb
We have reviewed the problem. We agree with a rewording in the menu bar, the title of the map gallery at the bottom of the start page, and the title top left below the logo on the map pages (example http://www.kartenportal.ch/it/maps/panorama/):

de: Kartentypen  (instead of: Wissenswertes // Wissenswertes über Karten)
en: Map types  (instead of: Worth knowing // Worth knowing about maps)
fr: Types de cartes  (instead of: Ce qu'il faut savoir // Ce qu'il faut savoir sur les cartes)
it: Tipi di mappe  (instead of: Informazioni interessanti // Informazioni interessanti sulla mappe)

Then you will be able to enlarge the menu bar font size, perhaps close to the size used beforehand.

**Comment by daliborjanak** [comment]
I changed translations and also I raised size of menu to original size.

**Comment by klokan** [comment]
Thanks @daliborjanak.

We need confirmation from Markus now.

Once confirmed - the same menu must be applied to the Search templates by @petrsloup

**Comment by ghost** [comment]
FROM:zb
Tested.

Menu can now be applied to the Search template.

**Comment by petrsloup** [comment]
Deployed to the temporary hosting:
http://klokan.github.io/maprank-client/
http://klokan.github.io/maprank-client/index.de.html
http://klokan.github.io/maprank-client/index.fr.html
http://klokan.github.io/maprank-client/index.it.html

**Comment by ghost** [comment]
FROM:zb
Tested.
