### ISSUE TITLE
Editions in the result list - issues with mouse hover

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#39]
There are unwanted mouse-over effects to be eliminated.

Reproduction: When one has a record with different editions shown, it is almost impossible to mark one of the editions and then to move the mouse to the left into the Detailansicht in order to click on the catalogue button. The reason is that any movement of the cursor highlights the edition next to the chosen one. See attached image, where the 1925 edition has been chosen but the user was unable to move the cursor to the catalogue button.

The problem could be solved when there is a separate line for each edition. In the example:

Plasselb
1:25 000
Eidg. Stabsbureau, 1884
Series: Topographischer Atlas der Schweiz
1884
1894
1917
1919
1921
1922
1924
1925
1931
etc.

This arrangement is still an improvement compared with the alpha version where all editions are scattered in the Trefferliste. Yet it allows to safely move the cursor to the left without affecting your intended selection.

**Comment by klokan** [comment]
I suggest to display only one "editions line" under the main record showing:

```
> another 9 editions
```

After user clicks on this "editions line" the complete list will open, with one edition per row to avoid mouse hover issues:

```
< another 9 editions
1884
1894
1917
1919
1921
1922
1924
1925
1931
```

The complete list of the editions can be again closed by clicking on the "editions line" with "another 9 editions" text.

@zb-markus: do you agree?

**Comment by klokan** [comment]
What should be exactly the label of the "editions line"?
"+ 9 older editions" or "another 9 editions", ...?

**Comment by zb-markus** [comment]
We agree with a single line for the other editions.

Because now the editions cannot be scanned by eye before the list has been opened, we suggest to show the _latest_ edition as the main entry in the Trefferliste, of course with regard to the time filter settings. All _earlier_ editions are then in the editions list that can be opened with mouse-click. Take care that the editions list is in chronological ascending order. 

Example: There are 6 editions of a map: 1900, 1920, 1940, 1960, 1980, 2000. Time filter is set to 1920-1970. The main entry is now the 1960 edition, i.e. the latest of those being within the selected time span. The edition list contains the 2 earlier editions that are within the selected time span:
1920
1940

Wording: We suggest for the editions line: "X earlier editions of this map ..." (where X is the number of earlier editions).

**Comment by klokan** [comment]
I am working on the visualisation.

**Comment by klokan** [comment]
Done
