### ISSUE TITLE
Welcome / Help dialog

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#58]
Text for Geosearch Help. The English has been approved by a native speaker.

It is intended that the marked words should be eyecatchers. They should be highlighted in some way your designer finds acceptable (for example bold type in 80% grey). The blue-marked term at the end is intended as a link to Kartenportal's map collections directory. The numbering corresponds to a small print screen – see the attached design template. A size of 250 x 150 px seems to be large enough.

---

Welcome to the search interface for maps held by Swiss libraries.
- What is the purpose of this tool?

This is the **virtual map catalogue** of Swiss map collections. You can search maps covering the entire world and ranging from late medieval manuscripts to current electronic maps. Maps of all types, scales and topics are available.
- How does it work?

[1] Searching is very easy indeed. Search either by entering a place-name in the top-left **Search Box** or by zooming and panning the large **Search Map**. Adjust the Search Map as accurately as possible to both the area and the zoom level required.

[2] Any action will immediately update the **Result List** on the right. The top entry is always the map that best fits your chosen area and zoom level. For **details** about a particular map, simply click the highlighted part. A bibliographic description and the list of libraries holding that particular map will open.

[3] For a further refinement of your search, three filters are available. The **Timeline** enables you to restrict your search to a specific publication period. Clicking the **Attributes** icon opens further filters: Full Text, Author, Publisher, Subject, and Map Scale. With the **Library** filter you may narrow the search to one of the main map collections.

You can always come back to these instructions by clicking the **Help** icon.
- Not found what you wanted?

If you were not able to find the correct map, you are welcome to call the map library of your choice. Staff will help to locate particularly old or rare maps that are sometimes not yet retrievable in library catalogues.

Please note that maps held by archives need to be accessed directly via the archive in question (see [address list](http://www.kartenportal.ch/libraries/)).

---

![help_vorschlag_nr](https://f.cloud.github.com/assets/59284/561538/f329d998-c490-11e2-926b-63f8e3f1e0c9.jpg)

**Comment by klokan** [comment]
The main points are mentioned very well, but I am afraid this text is still too long for displaying on the web. We may try to reformulate it and shorten it. @radimkacer Let's try how it looks on a mockup.

**Comment by zb-markus** [comment]
At least the last question and its text ("Not found what you wanted?") could be "closed" at the beginning. The user could then click in order to display the text (like the multiple editions in the Trefferliste).

Perhaps this works also with the text numbered [2] to [3], e.g.
-- [2] Finding the search results ... (click opens text "Any action ...")
-- [3] Refining the search query ... (click opens text "For a further ...")
However, #[1] should always be visible as this is the most important part.

**Comment by klokan** [comment]
After long internal discussion and several trials with mockups - I think the best would be to go in this direction:

![screen shot 2013-05-25 at 1 59 55 pm7](https://f.cloud.github.com/assets/59284/564107/e482ac58-c53f-11e2-936d-b5adb791c2c1.jpg)

@zb-markus please provide us with some feedback.

**Comment by zb-markus** [comment]
OK, we agree. Note that the contrast between text and background is high enough. A variant would be to have the text blocks within white speech balloons with text in black.

**Comment by klokan** [comment]
Implemetation of the positioning of the arrows has been very problematic.
Therefore the we changed the design:

![kartenportal-mappage-welcomebox03](https://f.cloud.github.com/assets/59284/901003/b9939d5c-fb74-11e2-8673-795401815d3b.jpg)
![kartenportal-mappage-welcomebox04](https://f.cloud.github.com/assets/59284/901004/b9ab58de-fb74-11e2-875f-01d9e2684772.jpg)

Between welcome and help will be a flip animation on modern browsers - the dialog will "rotate".

**Comment by zb-markus** [comment]
OK, we agree.

**Comment by klokan** [comment]
Done - in modern browsers there are cool animations.

**Comment by zb-markus** [comment]
We have some small amendments:

In the How does it work part, in nr. 1, the title should read: "Getting started". In the text, it should read: "There is also an Exact Area tool (1c)" instead of "There is also a tool ..."

Below the instructions 1 to 3, the following text is expected: "You can always come back to these instructions by clicking the Help icon."

In the About part, it should read: "You are welcome to contact the library of your choice" (i.e. omit the archives here).

We think the justified layout might become problematic in other languages such as French and German where words are usually much longer than in English. In those languages there will be less words on one line, and therefore wider gaps between words. Consider to prepare for wider columns.

**Comment by klokan** [comment]
Done.

**Comment by zb-markus** [comment]
We have again two test results just coming in:
- In the About part, it should read "You can search for maps covering ..." (insert "for"). This is a small improvement despite the text submitted originally has been written by a native speaker. We are sorry for any inconvenience this may cause for the translation process.
- The links at the bottom (About and How does it work?) should be better visible, either in bold font and/or larger font size.

**Comment by klokan** [comment]
ad 1) this must be done after the translation process is finished - it is now too late for this change on our side. English phrases in Search interface has been already locked. Task is moved into #82.

ad 2) We will use a larger font (16px)

**Comment by klokan** [comment]
Done and deployed.

**Comment by zb-markus** [comment]
Tested and accepted.
