### ISSUE TITLE
Front page - change of the main photo

### ISSUE THREAD

**Issue by klokan** [klokantech/kartenportal-tickets#6]
Here is a mockup of the frontpage with changed photo according the request:

![kartenportal-webdesign-v4-homepage18](https://f.cloud.github.com/assets/59284/401901/3724554c-a8ee-11e2-9a07-1bf2dd8ce7d8.jpg)

Visually the original photo is more balanced with the website, but there are reasons for changing it.

We need definitive confirmation from Susanne, if this should be used or the existing "girl" photo.

**Comment by ethbib-susanne** [comment]
Dear Petr

Markus and J could not access the ticket pages because you have sent us a wrong URL by e-mail. J sent an email on 12th april asking for the correct URL ... Finally J realized that J could find the kartenportal tickets searching with keywords. 

Here my answer:
J confirm the new phot for the frontpage. As we choose it for the maps on the table J would prefer if the picture was a little longer showing more of the maps on the table (see mockup below).

![frontpage](https://f.cloud.github.com/assets/4223790/408791/4837319c-ab3c-11e2-9c0f-a84711491215.jpg)

Best regrards 
Susanne

**Comment by klokan** [comment]
@radimkacer definitive version is required for you!

**Comment by klokan** [comment]
@JackuB Please integrate the foto from #22.

**Comment by JackuB** [comment]
Done
