### ISSUE TITLE
Missing maps in Trefferliste

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#70]
Some maps are missing in the Trefferliste despite their bounding-boxes fit within the search map.

Compare
(1) http://dev.klokantech.com/kartenportal/#bbox=-16.768652562500506,38.5891714406919,15.223539259765061,51.81388113039637&q=&date_from=1950&date_to=9999&scale_from=&scale_to=&libraries=Z06
with
(2) http://dev.klokantech.com/kartenportal/#bbox=-44.08418012500107,26.367732618258028,19.900203519530123,54.4288414092141&q=&date_from=1950&date_to=9999&scale_from=&scale_to=&libraries=Z06

The map of Berlin http://dev.klokantech.com/kartenportal/#id=130962589 is missing in case (1) but shows up in case (2), despite Berlin is completely depicted on the search map in case (1) as well.

**Comment by klokan** [comment]
The geographical query submitted to MapRank is specified by the blue rectangle visible when you are dragging the map or exactly by the select tool (under + and - buttons on the left).

In your examples the blue rectangle of the query in case (1) does not contain Berlin, and in case (2) it does.

This is therefore expected behaviour.

If you want to control exactly the area of query, please use the select tool.

**Comment by zb-markus** [comment]
We know of the blue search rectangle, but does the user knows as well? A user may think that the whole (or almost the whole) search map is taken into account. When the screen is small, the blue search rectangle is even smaller because there seems to be a standard distance between blue rectangle and map margin. We suggest that the standard distance should be halved, or in other words, that the blue search rectangle should be larger in relation to the search map.
