### ISSUE TITLE
Multiple attributes selected

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#73]
When more than one attribute in the attributes filter has been selected, only one (scale or full text) is visible in the blue box below. The fact that also other attributes such as a publisher or a subject have been selected is not visible. Moreover, it is not possible to delete only one attribute because clicking the X in the blue box deletes _all_ attributes selected.

Example:
http://dev.klokantech.com/kartenportal/#bbox=7.3207824707030795,46.429971268036994,8.320782465147544,46.835506455226636&q=adelboden publisher:kümmerly &date_from=1950&date_to=9999&scale_from=10000&scale_to=50000&libraries=

To do:
- it should be visible that more than one attribute has been selected
- it should be possible to delete a single attribute and retain the other attributes selected before

**Comment by klokan** [comment]
The purpose of the label is to alert that there are some attributes set - not to present all the configured attributes. It is the reset button.

If you want to see the complete list of attributes or change the values of individual attributes, then open the dialog by clicking on the icon above the label. Then you can remove or change them separately.

In fact we present in the label a long list of all the selected attributes already, but the attributes are not visible, because there is no space for all of them. See for example label with "a" and "b" at this link:
http://dev.klokantech.com/kartenportal/#bbox=1.123046875,42.67020112251145,15.498046795138862,49.85666091495874&q=b creator:a &date_from=1950&date_to=9999&scale_from=&scale_to=&libraries=

So reaction to the "To do":
- I am afraid there is not enough place in the label for displaying more then what is already displayed.
- It is already possible to delete single attribute and retain the other by opening again the dialog with the values by clicking on the icon in the toolbar above the label.

The blue labels are replacing single Reset button as specified in the Lastenheft F.34.

Unless a clear and simple solution is presented, this request must be postponed to future I am afraid.

**Comment by zb-markus** [comment]
When several attributes are selected, the blue box shows "X [full text]". The user expects that clicking the X closes the attribute [full text], while the other attributes remain selected. However, the click unexpectedly closes _all_ attributes. As developers we know that the attributes shoud be opened in order to close only one of them. But a user cannot know that and will learn only by trial and error. 

We must therefore find a solution to show that multiple attributes have been selected, and that clicking in the blue box will close all of them. In the moment the user selects two or more attributes, the label in the blue box should change to "X [all attributes]" or similar. This label should be language-specific.

Then we propose that single attributes (out of the slected range) can be closed without opening the attributes dialog. Try the following: The user moves the cursor over he blue box "X [all attributes]". After a certain waiting time, a larger overlay blue box opens with a line for each selected attribute, e.g.:
 X [full text attribute]
 X [subject attribute]
 X [scale attribute]
Then the user can move the cursor and close the attribute as required. The labels should be language-specific.

**Comment by zb-markus** [comment]
Could we have this issue open again, please?

**Comment by klokan** [comment]
If you want us to now keep the ticket open for future we can, but unless there is an idea for a clear and simple solution, this request must be postponed to future, I am afraid.

It would be possible to show something like first two letters from everything what is typed in the inputs or to introduce a similar simple workaround.

Another idea we were discussing: if more then one input boxes is filled in the Attributes dialog, the blue box will not have X anymore and on click it will open the Attributes dialog instead of removing all filters and the blue X will be present behind every single input box. But still, there is an issue with changing of behaviour of the blue box (direct removing of the filter limit as on others vs opening of a dialog) - which is against usability principles.

Because of the design I don't think we should show multiple X boxes or to make the X box for Attributes somehow bigger.

I am also afraid the proposed expandable X box with "waiting time" would be quite time consuming to implement and I am still not sure about the usability of this solution.

It would be good to discuss this issue with somebody - or even better don't tell him/her anything and just look over the shoulder, if he/she feels this is an issue and how long it takes him/her to realize the workaround with clicking on the filter again and deleting the individual input boxes.

In the Lastenheft F.34 "Alle Filtereinstellungen können mit einem Klick auf den Standardwert zurückgestellt werden" was proposed a single reset button for all filters together, estimated as 4 hours of work - and the solution which we have now is of a magnitude better - separate for time, filters and libraries.

**Comment by zb-markus** [comment]
- Closing all attributes: We think it still necessary that in the moment the user selects two or more attributes, the label in the blue box should change to "X [all attributes]" or similar. This label should be language-specific.
- Closing single attributes: The situation is quite difficult when more than one attribute has been selected but only one of them should be closed. We agree that there is no perfect solution in sight. Tests with newcomers seem to be a good idea.

**Comment by klokan** [comment]
Let's change the label if more then one attribute is selected.

**Comment by klokan** [comment]
@zb-markus Please test and validate.

**Comment by zb-markus** [comment]
Tested and accepted.
