### ISSUE TITLE
Trefferliste: earlier editions (link design)

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#80]
The link "Earlier editions of this map" in the Trefferliste is the only one with underline. It should fit better into the overall design of the system, perhaps when designed as a button (compare with issue #30).

**Comment by klokan** [comment]
I suggest we change this later on - together with map series update for ETH, because then we may need to add another button for series to open map series view...
We will have probably two buttons then: "Editions (5)" and "Map Index"?

**Comment by zb-markus** [comment]
We do not like to postpone this issue. We think that the button for the "Earlier editions of this map" is needed now.

**Comment by klokan** [comment]
OK. Please provide a mockup or a very clear instructions for how you want the link to look like.
The text for the button must be static and without any new functionality - we will change the look&feel according your wish.

Keep in mind the button must be displayed on two different shades of gray and on a blue gradient for a highlighted item, which makes it problematic for the design. It should not be too visible, because it represent a secondary action - which is less important. The main action you want people to do is to click on the whole record (highlighted with blue).

**Comment by zb-markus** [comment]
Of course I see the problem making a button for two different shades of grey (happily not 50) etc. When I opened this ticket I wrote that the present link "should fit better into the overall design of the system, perhaps when designed as a button". Actually, a button for the text is not a must but only one of the possible solutions. Perhaps the easiest solution is the use of arrow buttons. 

Try a right-pointing triangle left of the text "Earlier editions of this map (x)", while the text itself is not underlined and maybe even normal (not bold). When the user clicks on either the triangle or the text, the triangle turns down and the list becomes visible. Clicking again closes the list and turns the triangle to the right.

Colour: Try dark grey for the triangle (e.g. 60% to 80% black) that works with both background shades but is not dominant against the text.

**Comment by petrsloup** [comment]
Arrow implemented.

**Comment by klokan** [comment]
@zb-markus Please test and validate.

**Comment by zb-markus** [comment]
Tested and accepted.
