### ISSUE TITLE
Show maps with date coded after q

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#83]
We miss several 10,000 maps that are coded in MARC field 008 at position 06 with q. Examples:

http://www.swissbib.ch/TouchPoint/perma.do?q=0%3D%2213095442X%22
http://www.swissbib.ch/TouchPoint/perma.do?q=0%3D%22195687779%22

Maps coded with q are mainly old maps or sheets of map series held by ETH. Code q should be handled like code m, i.e. the years immediately following at positions 008/07-14 should be treated accordingly.

**Comment by klokan** [comment]
I expect the maps are indexed, but without the year information, because specification for this form of encoding of the year inside of the MARC record has not been provided until now.

@keosak Please implement this decoding of the year from field 008 on positions 07-14 after "q" character, it is practically the same as for "m". Relevant code: https://github.com/klokan/maprank-server/blob/master/bin/update_database.py#L405

We may need to re-run the complete harvesting via OAI again.

**Comment by keosak** [comment]
I have started the complete re-indexing. It should be done in about two hours.

**Comment by keosak** [comment]
Re-indexing done and the data are live on the site.

**Comment by klokan** [comment]
@zb-markus Please test and validate.

**Comment by zb-markus** [comment]
Tested and accepted.
